routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\UsersController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::resources([
    'clientes' => ClienteController::class,
    'users' => UsersController::class,
]);

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Empresa;
use DB;
use Illuminate\Http\Request;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $empresas = Empresa::all();
        return view('clientes.index',compact('empresas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clientes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'nombre' => ['required','string','max:255'],
            'rut'   => ['required','unique:empresas'],
            'email' => ['required','string'],
            'site'  => 'required'
        ]);
        $empresa = Empresa::create($request->all());
        $empresa->save();
        return redirect()->route('clientes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $usuarios = 
            DB::table('users')
            ->leftJoin('empresa_users','users.id','=','empresa_users.id_user')
            ->where('empresa_users.id_empresa','=',$id)
            ->paginate(10);
        return view('clientes.show',compact('usuarios'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cliente = Empresa::find($id);
        return view('clientes.edit',compact('cliente'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nombre' => ['required','string','max:255'],
            'rut'   => ['required','unique:empresas'],
            'email' => ['required','string'],
            'site'  => ['required','url']
        ]);
        $empresa = Empresa::find($id);
        $empresa->fill($request->all());
        $empresa->save();
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $empresa = Empresa::find($id)->delete();
        return redirect()->back();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/clientes/create.blade.php
@php
    $empresa = DB::table('empresa_users')->where('id_user','=',Auth::user()->id)->select('id_empresa')->get();
    if ($empresa[0]->id_empresa != 1) {
        $sitio = DB::table('empresas')->where('id','=',$empresa[0]->id_empresa)->select('site')->get();
        header("Status: 200 Redireccion Programada");
        //dd("Location: ".$sitio[0]->site);
        header("Location: ".$sitio[0]->site);
        exit;
    }
@endphp
<x-app-layout>
	<x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Clientes') }}
        </h2>
        <div class="card col-md-6">
        	<div class="card-body">
        		<div class="panel">
        			<form method="POST" action="{{route('clientes.store')}}">
        				@csrf
	                    <div class="form-inline d-flex justify-content-between">
	                        <label>Nombre: </label><input type="text" id="nombre" name="nombre" placeholder="nombre">
	                    </div>
	                    <div class="form-inline d-flex justify-content-between">
	                        <label>RUT: </label><input type="text" id="rut" name="rut" placeholder="xx.xxx.xxx-x">
	                    </div>
	                    <div class="form-inline d-flex justify-content-between">
	                        <label>Email: </label><input type="text" id="email" name="email" placeholder="correo@sitio.com">
	                    </div>
	                    <div class="form-inline d-flex justify-content-between">
	                        <label>Sitio: </label><input type="text" id="site" name="site" placeholder="127.0.0.1">
	                    </div>
	                    <br>
	                    <div class="form-inline d-flex justify-content-between">
	                    	<a href="{{route('clientes.index')}}" class="btn btn-info">Volver</a>
	                    	<button type="submit" class="btn btn-primary">Guardar</button>
	                    </div>
                    </form>
                </div>
        	</div>
        </div>
	</x-slot>
</x-app-layout>

resources/views/clientes/edit.blade.php
@php
    $empresa = DB::table('empresa_users')->where('id_user','=',Auth::user()->id)->select('id_empresa')->get();
    if ($empresa[0]->id_empresa != 1) {
        $sitio = DB::table('empresas')->where('id','=',$empresa[0]->id_empresa)->select('site')->get();
        header("Status: 200 Redireccion Programada");
        //dd("Location: ".$sitio[0]->site);
        header("Location: ".$sitio[0]->site);
        exit;
    }
@endphp
<x-app-layout>
	<x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Clientes') }}
        </h2>
        <div class="card col-md-6">
        	<div class="card-body">
        		<div class="panel">
        			<form method="POST" action="{{route('clientes.update',$empresa->id)}}">
        				@csrf
        				<input type="hidden" name="_method" value="PUT">
	                    <div class="form-inline d-flex justify-content-between">
	                        <label>Nombre: </label><input type="text" id="nombre" name="nombre" placeholder="nombre" value="{{$empresa->nombre}}">
	                    </div>
	                    <div class="form-inline d-flex justify-content-between">
	                        <label>RUT: </label><input type="text" id="rut" name="rut" placeholder="xx.xxx.xxx-x" value="{{$empresa->rut}}">
	                    </div>
	                    <div class="form-inline d-flex justify-content-between">
	                        <label>Email: </label><input type="text" id="email" name="email" placeholder="correo@sitio.com" value="{{$empresa->email}}">
	                    </div>
	                    <div class="form-inline d-flex justify-content-between">
	                        <label>Sitio: </label><input type="text" id="site" name="site" placeholder="127.0.0.1" value="{{$empresa->site}}">
	                    </div>
	                    <br>
	                    <div class="form-inline d-flex justify-content-between">
	                    	<a href="{{route('clientes.store')}}" class="btn btn-info">Volver</a>
	                    	<button type="submit" class="btn btn-primary">Guardar</button>
	                    </div>
                    </form>
                </div>
        	</div>
        </div>
	</x-slot>
</x-app-layout>

resources/views/clientes/index.blade.php
@php
    $empresa = DB::table('empresa_users')->where('id_user','=',Auth::user()->id)->select('id_empresa')->get();
    if ($empresa[0]->id_empresa != 1) {
        $sitio = DB::table('empresas')->where('id','=',$empresa[0]->id_empresa)->select('site')->get();
        header("Status: 200 Redireccion Programada");
        //dd("Location: ".$sitio[0]->site);
        header("Location: ".$sitio[0]->site);
        exit;
    }
@endphp
<x-app-layout>
	<x-slot name="header">
        <h2 class="d-flex font-semibold text-xl text-gray-800 leading-tight justify-content-between">
            {{ __('Clientes') }}
        </h2>
	</x-slot>
	<div class="flex justify-end">
    	<a class="btn btn-success" href="{{route('clientes.create')}}"><i class="fa fa-plus"></i></a>
    </div>
    @if(count($empresas))
    <div class="flex justify-center">    	
    	<div class="table-container table-responsive">
    		<table class="table table-striped rounded">
				<thead class="thead thead-dark rounded">
					<th>ID</th>
					<th>Nombre</th>
					<th>Rut</th>
					<th>Email</th>
					<th>Sitio</th>
					<th>Ultimo Update</th>
					<th>Acciones</th>
				</thead>
				<tbody>
				@foreach($empresas as $empresa)
					<tr class="bg-secondary rounded">
						<td><a href="{{route('users.show',$empresa->id)}}">{{$empresa->id}}</a></td>
						<td><a href="{{route('users.show',$empresa->id)}}">{{$empresa->nombre}}</a></td>
						<td><a href="{{route('users.show',$empresa->id)}}">{{$empresa->rut}}</a></td>
						<td><a href="{{route('users.show',$empresa->id)}}">{{$empresa->email}}</a></td>
						<td><a href="{{route('users.show',$empresa->id)}}">{{$empresa->site}}</a></td>
						<td><a href="{{route('users.show',$empresa->id)}}">{{$empresa->updated_at}}</a></td>
						<td class="form-inline">
							<button type="button" class="btn btn-sm btn-info" data-toggle="modal" data-target="#create{{$empresa->id}}">
							  <i class="ni ni-single-02"></i>
							</button>
							<button type="button" class="btn btn-sm btn-warning" data-toggle="modal" data-target="#edit{{$empresa->id}}">
							  <i class="ni ni-settings"></i>
							</button>
							<button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete{{$empresa->id}}">
							  <i class="fa fa-trash"></i>
							</button>
							<!-- Modal -->
						<div class="modal fade" id="create{{$empresa->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
						  <div class="modal-dialog" role="document">
						    <div class="modal-content">
						      <div class="modal-header">
						        <h5 class="modal-title" id="exampleModalLabel">Agregar Usuario</h5>
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
						        <div class="panel">
				        			<form method="POST" action="{{route('users.store')}}">
				        				@csrf
					                    <div class="form-inline d-flex justify-content-between">
					                        <label>Nombre: </label><input type="text" id="nombre" name="nombre" placeholder="nombre">
					                    </div>
					                    <div class="form-inline d-flex justify-content-between">
					                        <label>Email: </label><input type="text" id="email" name="email" placeholder="correo@sitio.com">
					                    </div>
					                    <div class="form-inline d-flex justify-content-between">
					                        <label>Sitio: </label><input type="text" id="site" name="site" placeholder="127.0.0.1">
					                    </div>
					                    <br>
					                    <div class="form-inline d-flex justify-content-between">
					                    	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					                    	<button type="submit" class="btn btn-primary">Guardar</button>
					                    </div>
				                    </form>
				                </div>
						      </div>
						    </div>
						  </div>
						</div>
						<!-- Modal -->
						<div class="modal fade" id="edit{{$empresa->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
						  <div class="modal-dialog" role="document">
						    <div class="modal-content">
						      <div class="modal-header">
						        <h5 class="modal-title" id="exampleModalLabel">Editar Empresas</h5>
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
						        <form method="POST" action="{{route('clientes.update',$empresa->id)}}">
			        				@csrf
			        				<input type="hidden" name="_method" value="PUT">
				                    <div class="form-inline d-flex justify-content-between">
				                        <label>Nombre: </label><input type="text" id="nombre" name="nombre" placeholder="nombre" value="{{$empresa->nombre}}">
				                    </div>
				                    <div class="form-inline d-flex justify-content-between">
				                        <label>RUT: </label><input type="text" id="rut" name="rut" placeholder="xx.xxx.xxx-x" value="{{$empresa->rut}}">
				                    </div>
				                    <div class="form-inline d-flex justify-content-between">
				                        <label>Email: </label><input type="text" id="email" name="email" placeholder="correo@sitio.com" value="{{$empresa->email}}">
				                    </div>
				                    <div class="form-inline d-flex justify-content-between">
				                        <label>Sitio: </label><input type="text" id="site" name="site" placeholder="127.0.0.1" value="{{$empresa->site}}">
				                    </div>
				                    <br>
				                    <div class="form-inline d-flex justify-content-between">
				                    	<a href="{{route('clientes.store')}}" class="btn btn-info">Volver</a>
				                    	<button type="submit" class="btn btn-primary">Guardar</button>
				                    </div>
			                    </form>
						      </div>
						    </div>
						  </div>
						</div>
						<!-- Modal -->
						<div class="modal fade" id="delete{{$empresa->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
						  <div class="modal-dialog" role="document">
						    <div class="modal-content">
						      <div class="modal-header">
						        <h5 class="modal-title" id="exampleModalLabel">Eliminar Usuario</h5>
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
						        ...
						      </div>
						    </div>
						  </div>
						</div>
						</td>
						
					</tr>
				@endforeach
				</tbody>
			</table>
    	</div>
    </div>
	@else
	NO HAY NAAADI!
	@endif
</x-app-layout>

resources/views/clientes/show.blade.php
@php
    $empresa = DB::table('empresa_users')->where('id_user','=',Auth::user()->id)->select('id_empresa')->get();
    if ($empresa[0]->id_empresa != 1) {
        $sitio = DB::table('empresas')->where('id','=',$empresa[0]->id_empresa)->select('site')->get();
        header("Status: 200 Redireccion Programada");
        //dd("Location: ".$sitio[0]->site);
        header("Location: ".$sitio[0]->site);
        exit;
    }
@endphp
<x-app-layout>
	<x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Clientes') }}
            <a class="btn btn-primary" href="{{route('clientes.store')}}">Agregar</a>
        </h2>
        @if(count($usuarios))
        <div class="card">
        	<div class="card-body table-container">
        		<table class="table table-responsive table-striped rounded">
					<thead class="thead thead-dark rounded">
						<th>ID</th>
						<th>Nombre</th>
						<th>Email</th>
						<th>Ultimo Update</th>
						<th>Acciones</th>
					</thead>
					<tbody>
					@foreach($usuarios as $usuario)
						<tr class="bg-warning text-white rounded">
							<td>{{$usuario->id}}</td>
							<td>{{$usuario->name}}</td>
							<td>{{$usuario->email}}</td>
							<td>{{$usuario->updated_at}}</td>
							
						</tr>
					@endforeach
					</tbody>
				</table>
        	</div>
        </div>
		@else
		NO HAY NAAADI!
		@endif
	</x-slot>
</x-app-layout>